import { IClass, IMeetingDate, IMeetingTime } from '../src/public/js/Class';

export let baseClassJson: IClass = {
    quarter: '2194',
    subject: 'IST',
    catalogNo: ' 468',
    classSection: '01',
    textbook: '',
    employeeId: '001343367',
    classStartTime: '6:00 PM',
    classEndTime: '7:50 PM',
    enrolledCapacity: 30,
    enrolledTotal: 28,
    waitlistCapacity: 100,
    waitlistTotal: 1,
    classMeetingNo: 1,
    csuUnits: 4,
    amount: 0,
    courseId: '000001',
    sessionCode: '1',
    description: 'ACCT GOVT & NONPROFIT ORG',
    ssrComponent: 'SEM',
    campus: 'MAIN',
    instructionMode: 'OL',
    facilityId: 'JB0113',
    mon: 'Y',
    tues: 'N',
    wed: 'Y',
    thurs: 'N',
    fri: 'N',
    sat: 'N',
    sun: 'N',
    instructorName: 'Bakeman, Melissa',
};

export const classJson: IClass = {
    quarter: '2194',
    subject: 'ACCT',
    catalogNo: ' 468',
    classSection: '01',
    textbook: '',
    employeeId: '001343367',
    classStartTime: '6:00 PM',
    classEndTime: '7:50 PM',
    enrolledCapacity: 30,
    enrolledTotal: 28,
    waitlistCapacity: 100,
    waitlistTotal: 1,
    classMeetingNo: 1,
    csuUnits: 4,
    amount: 0,
    courseId: '000001',
    sessionCode: '1',
    description: 'ACCT GOVT & NONPROFIT ORG',
    ssrComponent: 'SEM',
    campus: 'MAIN',
    instructionMode: 'P',
    facilityId: 'JB0113',
    mon: 'Y',
    tues: 'N',
    wed: 'Y',
    thurs: 'N',
    fri: 'N',
    sat: 'N',
    sun: 'N',
    instructorName: 'Dyck, Harold',
};
export const classPDC: IClass = {
    quarter: '2192',
    subject: 'ECON',
    catalogNo: ' 468',
    classSection: '01',
    textbook: '',
    employeeId: '001343367',
    classStartTime: '6:00 PM',
    classEndTime: '7:50 PM',
    enrolledCapacity: 30,
    enrolledTotal: 28,
    waitlistCapacity: 100,
    waitlistTotal: 1,
    classMeetingNo: 1,
    csuUnits: 4,
    amount: 0,
    courseId: '000001',
    sessionCode: '1',
    description: 'ACCT GOVT & NONPROFIT ORG',
    ssrComponent: 'SEM',
    campus: 'PALM',
    instructionMode: 'P',
    facilityId: 'JB0113',
    mon: 'N',
    tues: 'Y',
    wed: 'N',
    thurs: 'Y',
    fri: 'N',
    sat: 'N',
    sun: 'N',
    instructorName: 'Coates, Breena',
};

export let meetingDates: IMeetingDate = {
    all: true,
    mon: false,
    tue: false,
    wed: false,
    thu: false,
    fri: false,
    sat: false,
    sun: false,
};

export const meetingTimes: IMeetingTime = {
    all: false,
    beforeNoon: true,
    afterNoon: false,
    evening: true,
};
