name: Push class search data to BigQuery
on:
  schedule:
    - cron: '59 23 */1 * *'
jobs:
  request:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://csusb-class-schedule.df.r.appspot.com/export-to-bigquery'
          method: 'GET'
