name: Deploy to production environment 
on:
  push:
    branches:
      - stg
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]
        containers: [1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: webpack --config ./webpack.production.config.js
    - run: npm run build
    - run: npm run test
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: csusb-class-schedule
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLI: gsutil
      with:
        args: -h "Cache-Control:no-cache,max-age=0" mv -a public-read dist/public/js/course-scheduling-app.js gs://csusb-class-schedule.appspot.com/course-scheduling-app-prod.js
        args: -h "Cache-Control:no-cache,max-age=0" mv -a public-read dist/public/js/course-scheduling-app.js.map gs://csusb-class-schedule.appspot.com/course-scheduling-app.js.map

