name: Monitor class schedule on production
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [13.x]
        containers: [1]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check for classes
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          spec: cypress/integration/CampusTests.js
          env: url=https://www.csusb.edu/class-schedule?bot=true
          config: baseUrl=https://www.csusb.edu/class-schedule
