name: Browser tests
on:
  push:
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]
        containers: [1]
    env:
      WEBDX_DEPARTMENT_PEOPLE_CLIENT_PASSWORD: ${{ secrets.WEBDX_DEPARTMENT_PEOPLE_CLIENT_PASSWORD }}
      WEBDX_DEPARTMENT_PEOPLE_CLIENT_SECRET: ${{ secrets.WEBDX_DEPARTMENT_PEOPLE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: webpack
        env:
          WEBDX_DEPARTMENT_PEOPLE_CLIENT_PASSWORD: ${{ secrets.WEBDX_DEPARTMENT_PEOPLE_CLIENT_PASSWORD }}
          WEBDX_DEPARTMENT_PEOPLE_CLIENT_SECRET: ${{ secrets.WEBDX_DEPARTMENT_PEOPLE_CLIENT_SECRET }}
      - run: npm run build
        env:
          WEBDX_DEPARTMENT_PEOPLE_CLIENT_PASSWORD: ${{ secrets.WEBDX_DEPARTMENT_PEOPLE_CLIENT_PASSWORD }}
          WEBDX_DEPARTMENT_PEOPLE_CLIENT_SECRET: ${{ secrets.WEBDX_DEPARTMENT_PEOPLE_CLIENT_SECRET }}
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
          env: url=http://localhost:3000
