name: Browser tests 
on:
  push:
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]
        containers: [1]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: cypress-io/github-action@v1
      with:
        browser: chrome
        headless: true
